package com.springbank.entity;

// Generated Jul 9, 2009 10:23:16 PM by Hibernate Tools 3.2.0.b9

/**
 * Account generated by hbm2java
 */
public class Account implements Entity {

	private long accountId;

	private Customer customer = new Customer();

	private String accountNumber;

	private double accountBalance;

	public Account() {
	}

	public Account(long accountId, Customer customer, String accountNumber,
			double accountBalance) {
		this.accountId = accountId;
		this.customer = customer;
		this.accountNumber = accountNumber;
		this.accountBalance = accountBalance;
	}

	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public double getAccountBalance() {
		return this.accountBalance;
	}

	public void setAccountBalance(double accountBalance) {
		this.accountBalance = accountBalance;
	}

	public void bindRelation() {

	}

}
