package com.springbank.entity;

// Generated Jul 9, 2009 10:23:16 PM by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements Entity {

	private long customerId;

	private String customerNumber;

	private String customerPassword;

	private String customerName;

	private String customerSurname;

	private String customerAddress;

	private Set accounts = new HashSet(0);

	public Customer() {
	}

	public Customer(long customerId, String customerNumber,
			String customerPassword, String customerName,
			String customerSurname, String customerAddress) {
		this.customerId = customerId;
		this.customerNumber = customerNumber;
		this.customerPassword = customerPassword;
		this.customerName = customerName;
		this.customerSurname = customerSurname;
		this.customerAddress = customerAddress;
	}

	public Customer(long customerId, String customerNumber,
			String customerPassword, String customerName,
			String customerSurname, String customerAddress, Set accounts) {
		this.customerId = customerId;
		this.customerNumber = customerNumber;
		this.customerPassword = customerPassword;
		this.customerName = customerName;
		this.customerSurname = customerSurname;
		this.customerAddress = customerAddress;
		this.accounts = accounts;
	}

	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public String getCustomerNumber() {
		return this.customerNumber;
	}

	public void setCustomerNumber(String customerNumber) {
		this.customerNumber = customerNumber;
	}

	public String getCustomerPassword() {
		return this.customerPassword;
	}

	public void setCustomerPassword(String customerPassword) {
		this.customerPassword = customerPassword;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerSurname() {
		return this.customerSurname;
	}

	public void setCustomerSurname(String customerSurname) {
		this.customerSurname = customerSurname;
	}

	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

	public void bindRelation() {
		this.accounts = new HashSet(this.accounts);
	}

}
