package com.springbank.entity;

// Generated Jul 9, 2009 10:23:16 PM by Hibernate Tools 3.2.0.b9

/**
 * Operator generated by hbm2java
 */
public class Operator implements Entity {

	private long operatorId;

	private String operatorAlias;

	private String operatorPassword;

	private String operatorFullname;

	public Operator() {
	}

	public Operator(long operatorId, String operatorAlias,
			String operatorPassword, String operatorFullname) {
		this.operatorId = operatorId;
		this.operatorAlias = operatorAlias;
		this.operatorPassword = operatorPassword;
		this.operatorFullname = operatorFullname;
	}

	public long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(long operatorId) {
		this.operatorId = operatorId;
	}

	public String getOperatorAlias() {
		return this.operatorAlias;
	}

	public void setOperatorAlias(String operatorAlias) {
		this.operatorAlias = operatorAlias;
	}

	public String getOperatorPassword() {
		return this.operatorPassword;
	}

	public void setOperatorPassword(String operatorPassword) {
		this.operatorPassword = operatorPassword;
	}

	public String getOperatorFullname() {
		return this.operatorFullname;
	}

	public void setOperatorFullname(String operatorFullname) {
		this.operatorFullname = operatorFullname;
	}

	public void bindRelation() {

	}

}
